### ISSUE TITLE
Disable beeping sound

### ISSUE THREAD

**Issue by rnazali** [martyr-deepin/deepin-terminal-gtk#164]
A loud  beeping sound will play when say, pressing backspace when no character is typed, or when pressing `tab` button for suggestion but no matched pattern is exist.

This beeping seems not related with current volume, so the beep still playing even if I muted the speaker.

I had tried to disable it by running `rmmod pcspkr` on startup or bash login, and it did works. But the beep remain plays when I entered different environment, say, with `less` command, or when entering root with `sudo su`.

I was looking a way to *permanently* disable the beep.

Let me know if I missed something.

**Comment by BLumia** [comment]
https://linuxconfig.org/turn-off-beep-bell-on-linux-terminal if you don't want the beep sound on whatever terminal emulator you'll use.

Or maybe add a config option to disable audible bell just for deepin-terminal?

**Comment by rnazali** [comment]
@BLumia  Thanks for the answer.

Sadly I have also tried that link. The beeping still continues.

I may be the one missing here though.

> https://linuxconfig.org/turn-off-beep-bell-on-linux-terminal if you don't want the beep sound on whatever terminal emulator you'll use.
> 
> Or maybe add a config option to disable audible bell just for deepin-terminal?

**Comment by BLumia** [comment]
@wangjia12

**Comment by BLumia** [comment]
There is a [`Vte.Terminal.set_audible_bell()`](https://valadoc.org/vte-2.91/Vte.Terminal.set_audible_bell.html) for that purpose and it can be very easy to implemented (take [this](https://github.com/linuxdeepin/deepin-terminal/commit/16cf3780b225baf701b6725725aaf5a836e042d1) as reference). I would like to help add a new config option for this but I'm quite busy these days, any patches via Pull Request are welcome!

**Comment by BLumia** [comment]
Should be fixed in the next update :)

**Comment by rnazali** [comment]
I really appreciate it.

**Comment by rodrigondec** [comment]
Is this up already?

**Comment by BLumia** [comment]
> Is this up already?

Should be fixed in 3.2.7, which distro are you using now? Some distro like Arch already updated their package. Deepin will release the update in the 15.10.2 release cycle (upcoming days).

**Comment by rodrigondec** [comment]
Deepin 15.10.1. I'll wait for the 15.10.2 then, thx

**Comment by maxjf1** [comment]
I was able to remove the beep on terminal, but i sill have it when typing. I have an Brazilian keyboard, when i press <kbd>~</kbd> + <kbd>W</kbd> (or some letter that doesn't accept ~) it still beeps everywhere. It happens with any accentuation with an wrong character.

**Comment by rodrigondec** [comment]
On mine was fixed. ABNT2 Keyboard.

Which version of the deepin is yours?

**Comment by maxjf1** [comment]
> On mine was fixed. ABNT2 Keyboard.
> 
> Which version of the deepin is yours?

![image](https://user-images.githubusercontent.com/6114888/65510532-8a258780-deab-11e9-8044-ba404259627e.png)

**Comment by rodrigondec** [comment]
@maxjf1 

Open another issue, this one is closed and about the beeping in general while this case is about the `~` character. Don't forget do refer this issue on the new one

**Comment by rodrigondec** [comment]
On mine didn't happen the beep with `~` + `w`

**Comment by maxjf1** [comment]
> On mine didn't happen the beep with `~` + `w`

do you have an portuguese(Brazil) keyboard? try to enable it and reproduce it. normally, `~+a=ã` and `~+w` doesn't generate nothing but the beep. Also, make sure you have energy saver off and sound on. (after reproducing it, you can disable sound and it will still continue)

**Comment by rodrigondec** [comment]
Where do I enable it? Can't find it now

Ps.: my speaker is working fine. Tested with `speaker-test -t sine -f 500 -l 1`

**Comment by maxjf1** [comment]
You can enable it in "keyboard layout > add keyboard layout"

And i am not talking about the normal speakers, i'm talking about the internal beep that old machines and some laptops have. to reproduce it you need to disable battery save and enable sound for some reason.

![image](https://user-images.githubusercontent.com/6114888/65627095-09e34d00-dfa5-11e9-92bf-8117923f44b2.png)

**Comment by rodrigondec** [comment]
Yes, I as refering to `pcspeaker` also known as buzzer.

Didn't mean how to enable the keyboard. My keyboard is ABNT2 and I'm using Português (Brasil) as my layout. 

I don't have the beep enabled on my deepin. And I don't recall how to enable it

**Comment by maxjf1** [comment]
hmm, i don't know either, and also, sometimes i can't get the beep, sometimes it stops. This is the worst part, because it is always very loud and scaries me :laughing:

**Comment by cyruzin** [comment]
> I was able to remove the beep on terminal, but i sill have it when typing. I have an Brazilian keyboard, when i press ~ + W (or some letter that doesn't accept ~) it still beeps everywhere. It happens with any accentuation with an wrong character.

Same issue here on Deeping 15.11.

**Fixed doing this:**

Open the terminal and type this:

`xset -b`

Then open your .xprofile file 

`sudo vim ~/.xprofile`

add this line to your .xprofile

`xset -b`

**Comment by maxjf1** [comment]
i fixed it by removing completly from linux the beep support (i don't remember now how, but i think it was some kernel package to remove).

--EDIT--

The BEEP is back! I don't know what to do anymore.
